name: OVHDeploy

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Create .env
        run: cp .env.example .env

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set application encryption key
        run: php artisan key:generate --ansi

      - name: Create storage link
        run: php artisan storage:link

      - name: Run migrations
        run: php artisan migrate --force

      - name: Install node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Deploy PHP to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R $USER:www-data /var/www/html
            sudo chmod -R 766 /var/www/html
            cd /var/www/html/Car-sales-platform-laravel
            git fetch --all
            if git rev-parse -q --verify "refs/tags/${{ github.event.release.tag_name }}"; then
              git checkout ${{ github.event.release.tag_name }}
            else
              git checkout master
            fi
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm ci
            npm run build
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 766 /var/www/html

